### ISSUE TITLE
BetterChannelList crashes entering servers

### ISSUE THREAD

**Issue by blackxfiied** [arg0NNY/DiscordPlugins#116] opened 2024-11-07 09:36 UTC
### Plugin:

📜 BetterChannelList

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.1.8

### What client are you using?

🔵 Stable

### Describe the bug

Self-explanatory title, BetterChannelList crashes Discord upon entering any server, some users have reported different cases on different servers (#114, #111) 

This issue is open for proper tracking's sake

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by sirlupusdev** [comment] 2024-11-07 17:23
As you said yourself, this is already reported in #114 (for the plugin), we'll be using that issue for potential updates or fixes.
Duplicate of #114

**Comment by sirlupusdev** [comment] 2024-11-07 17:24
Duplicate of #114

**Closed** 2024-11-07 17:24 UTC
Labels: bug
