### ISSUE TITLE
Error useStateFromStores

### ISSUE THREAD

**Issue by BySwiizen** [arg0NNY/DiscordPlugins#92] opened 2024-06-19 13:27 UTC
### Plugin:

📑 BetterGuildTooltip

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.0.3

### What client are you using?

🔵 Stable

### Describe the bug

Hi! Since the new discord update, when starting the software I have an error displayed on the BetterGuildTooltip plugin stating that compilation is impossible.

### Additional comments

TypeError: Cannot destructure property 'useStateFromStores' of 'WebpackModules.getByProps(...)' as it is undefined.
    at plugin (betterdiscord://plugins/BetterGuildTooltip.plugin.js:107:21)
    at eval (betterdiscord://plugins/BetterGuildTooltip.plugin.js:291:16)
    at eval (betterdiscord://plugins/BetterGuildTooltip.plugin.js:292:7)
    at eval (betterdiscord://plugins/BetterGuildTooltip.plugin.js:293:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by Leah96xxx** [comment] 2024-06-19 15:36
Looks like this is caused by Discord changing `useStateFromStores`. See this issue on another plugin: https://github.com/unknown81311/BetterMediaPlayer/issues/17

**Comment by arg0NNY** [comment] 2024-06-19 21:35
Fixed in cc4ac53622196ff2b8137a8986db42dce15b2b19

**Closed by arg0NNY** 2024-06-19 21:35 UTC
Labels: bug
