### ISSUE TITLE
Erro no BetterAnimations.plugin

### ISSUE THREAD

**Issue by AshSlake** [arg0NNY/DiscordPlugins#91] opened 2024-06-19 03:41 UTC
### Plugin:

🎞️ BetterAnimations

### What version of BetterDiscord are you using?

1.1.19

### What version of the selected plugin(s) are you using (if applicable)?

1.1.19

### What client are you using?

🔵 Stable

### Describe the bug

erro ao compilar o plugin !!

`Paulo_Henrique
ash_slake
Não perturbar
BDFDBv3.6.6por DevilBro

Required Library for DevilBro's Plugins
BetterAnimationsv1.1.19por arg0NNY

An error was encountered while trying to load this plugin.
Improves your whole Discord experience. Adds highly customizable switching animations between guilds, channels, etc. Introduces smooth new message reveal animations, along with popout animations, and more.
CallTimeCounterv0.0.6por QWERT

Shows how much time you are in a voice chat.
FriendNotificationsv2.0.0por DevilBro

Shows a Notification when a Friend or a User, you choose to observe, changes their Status
SplitLargeMessagesv1.8.2por DevilBro

Allows you to enter larger Messages, which will automatically split into several smaller Messages
ZeresPluginLibraryv2.0.21por Zerebos

Gives other plugins utility functions.
TypeError: Cannot destructure property 'Route' of 'WebpackModules.getByProps(...)' as it is undefined.
    at plugin (betterdiscord://plugins/BetterAnimations.plugin.js:126:28)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2010:16)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2011:7)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2012:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201`

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by RobertoGol** [comment] 2024-06-19 15:04
please look at line 13 it says there is an error there

**Comment by sirlupusdev** [comment] 2024-06-19 15:49
Duplicate of #90

**Closed** 2024-06-19 15:49 UTC
Labels: bug
